### ISSUE TITLE
Migrate to the new kivy garden structure

### ISSUE THREAD

**Issue by AndreMiras** [kivy-garden/garden.rotabox#1]
Nice to see the flower is getting some love recently :heart: 
Flower are now getting migrated to a new structure see https://kivy-garden.github.io/#guideformigratingflowersfromlegacystructure
Put simply it makes it standardise and simplifies its installation. Things will now go under `site-packages/` but still under the `kivy_garden/` namespace. Also makes it possible to simply `pip install` the package e.g. `pip install kivy-garden.rotabox`. Let us know if you can/want look into it so we can create the repo under `kivy-garden`

**Comment by unjuan** [comment]
Thanks!
I'm sorry but my flower doesn't have a `pip install` option, because I don't have the time/patience to figure out how to do it (or figure out why `pip install` doesn't even work in my system!) . 
Also, the flower requires a (provided) editor which I can't imagine how to introduce in the whole procedure.
I read the 'guide for migrating flowers', hoping that all that was required of me was just a permission and some file restructuring, but I couldn't understand the half of it.
So, again, thank you but I'm not able to do this right now.

**Comment by AndreMiras** [comment]
No problem, ping me when you're up for it so we can help with that. We already migrated few flowers
